//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diary.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неможливо зберегти зміни. Повторіть спробу..
        /// </summary>
        public static string DBError {
            get {
                return ResourceManager.GetString("DBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недійсне запрошення..
        /// </summary>
        public static string FailInvite {
            get {
                return ResourceManager.GetString("FailInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний логін або пароль.
        /// </summary>
        public static string FailLoginOrPassword {
            get {
                return ResourceManager.GetString("FailLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з таким email вже зареєстрований на сайті.
        /// </summary>
        public static string GetEmailForInvitation_ExitingEmail {
            get {
                return ResourceManager.GetString("GetEmailForInvitation_ExitingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректно введені дані. Перевірте правильність введених даних та повторіть спробу.
        /// </summary>
        public static string ModelIsNotValid {
            get {
                return ResourceManager.GetString("ModelIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з таким email не зареєстрований на сайті.
        /// </summary>
        public static string NonexistentEmail {
            get {
                return ResourceManager.GetString("NonexistentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з даним email вже зареєстрований. Введіть інший email.
        /// </summary>
        public static string Register_ExitingEmail {
            get {
                return ResourceManager.GetString("Register_ExitingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з даним нікнеймом вже зареєстрований. Введіть інший нікнейм.
        /// </summary>
        public static string Register_ExitingUserName {
            get {
                return ResourceManager.GetString("Register_ExitingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невдалось створити користувача. Перевірте дані на коректність введення.
        /// </summary>
        public static string UserDidNotCreate {
            get {
                return ResourceManager.GetString("UserDidNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач не знайдений.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
